# Generated by Django 5.1.7 on 2025-04-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
