# Generated by Django 5.1.7 on 2025-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_course_application_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='undergraduate', max_length=20),
        ),
    ]
